language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - git status
  - git checkout master
  - git status
  - npm run gulp
  - git status
  - git add .
  - git status
